[pytest]
testpaths = tests
addopts = -q
filterwarnings =
    ignore::DeprecationWarning:holowizard.*
    ignore:Conversion of an array with ndim > 0 to a scalar is deprecated:DeprecationWarning
    ignore:Creating a dataset without passing data or dtype is deprecated:h5py.h5py_warnings.H5pyDeprecationWarning
